"""
Report Generator Module.

Generates text and CSV reports for automation runs.
"""

import csv
import logging
from datetime import datetime
from pathlib import Path
from typing import List, Optional

from app.models import BatchResult, TaskResult


class ReportGenerator:
    """
    Generates run reports in text and CSV formats.

    Reports are stored in the 'reports' directory with timestamp-based names.
    """

    def __init__(
        self,
        reports_dir: Path = None,
        logger: Optional[logging.Logger] = None
    ) -> None:
        """
        Initialize ReportGenerator.

        Args:
            reports_dir: Directory to store reports (default: ./reports).
            logger: Optional logger instance.
        """
        self.reports_dir = reports_dir or Path("reports")
        self.logger = logger or logging.getLogger(__name__)

        # Ensure reports directory exists
        self.reports_dir.mkdir(exist_ok=True)

    def generate_run_report(
        self,
        results: List[BatchResult],
        filename: str = None
    ) -> Path:
        """
        Generate a text report for a run.

        Args:
            results: List of BatchResult from the run.
            filename: Optional custom filename.

        Returns:
            Path to the generated report file.
        """
        if not filename:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"run_{timestamp}.txt"

        report_path = self.reports_dir / filename

        with open(report_path, "w", encoding="utf-8") as f:
            f.write("=" * 60 + "\n")
            f.write("FB Auto Invite - Run Report\n")
            f.write("=" * 60 + "\n")
            f.write(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write("\n")

            # Summary
            total_accounts = sum(b.total_accounts for b in results)
            total_successful = sum(b.successful for b in results)
            total_failed = sum(b.failed for b in results)
            total_invites = sum(b.total_invites for b in results)
            total_duration = sum(b.duration for b in results)

            f.write("SUMMARY\n")
            f.write("-" * 40 + "\n")
            f.write(f"Total Batches:    {len(results)}\n")
            f.write(f"Total Accounts:   {total_accounts}\n")
            f.write(f"Successful:       {total_successful}\n")
            f.write(f"Failed:           {total_failed}\n")
            f.write(f"Total Invites:    {total_invites}\n")
            f.write(f"Total Duration:   {total_duration:.1f}s ({total_duration/60:.1f}m)\n")
            f.write("\n")

            # Batch details
            for batch in results:
                f.write(f"\nBATCH {batch.batch_number}\n")
                f.write("-" * 40 + "\n")
                f.write(f"Accounts: {batch.total_accounts} | ")
                f.write(f"OK: {batch.successful} | ")
                f.write(f"Failed: {batch.failed} | ")
                f.write(f"Invites: {batch.total_invites}\n")

                for result in batch.results:
                    status = "OK" if result.success else "FAIL"
                    display_name = result.account.display_name
                    f.write(f"  [{status}] {display_name}: ")
                    f.write(f"{result.invites_sent} invites")
                    if result.error:
                        f.write(f" | Error: {result.error}")
                    f.write("\n")

            f.write("\n" + "=" * 60 + "\n")
            f.write("Report generated by FB Auto Invite v3.0\n")

        self.logger.info(f"Report generated: {report_path}")
        return report_path

    def generate_csv_report(
        self,
        results: List[BatchResult],
        filename: str = None
    ) -> Path:
        """
        Generate a CSV report for a run.

        Args:
            results: List of BatchResult from the run.
            filename: Optional custom filename.

        Returns:
            Path to the generated CSV file.
        """
        if not filename:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"run_{timestamp}.csv"

        report_path = self.reports_dir / filename

        with open(report_path, "w", encoding="utf-8", newline="") as f:
            writer = csv.writer(f)

            # Header
            writer.writerow([
                "Batch",
                "Account",
                "Label",
                "Status",
                "Invites",
                "Duration",
                "Error"
            ])

            # Data rows
            for batch in results:
                for result in batch.results:
                    writer.writerow([
                        batch.batch_number,
                        result.account.debugger_address,
                        result.account.label or "",
                        "OK" if result.success else "FAIL",
                        result.invites_sent,
                        f"{result.duration:.1f}",
                        result.error or ""
                    ])

        self.logger.info(f"CSV report generated: {report_path}")
        return report_path

    def generate_daily_summary(self, date: datetime = None) -> Path:
        """
        Generate a daily summary report.

        Args:
            date: Date for the summary (default: today).

        Returns:
            Path to the generated summary file.
        """
        from app.database import db

        date = date or datetime.now()
        date_str = date.strftime("%Y%m%d")
        filename = f"daily_summary_{date_str}.txt"
        report_path = self.reports_dir / filename

        # Get statistics from database
        daily_stats = db.get_daily_invite_counts(date.date())

        with open(report_path, "w", encoding="utf-8") as f:
            f.write("=" * 60 + "\n")
            f.write(f"FB Auto Invite - Daily Summary for {date.strftime('%Y-%m-%d')}\n")
            f.write("=" * 60 + "\n\n")

            f.write("INVITE COUNTS BY ACCOUNT\n")
            f.write("-" * 40 + "\n")

            total_invites = 0
            for account_addr, count in daily_stats.items():
                f.write(f"  {account_addr}: {count} invites\n")
                total_invites += count

            f.write("\n")
            f.write(f"TOTAL: {total_invites} invites\n")
            f.write("\n" + "=" * 60 + "\n")

        self.logger.info(f"Daily summary generated: {report_path}")
        return report_path

    def get_recent_reports(self, limit: int = 10) -> List[Path]:
        """
        Get list of recent report files.

        Args:
            limit: Maximum number of reports to return.

        Returns:
            List of report file paths, newest first.
        """
        reports = list(self.reports_dir.glob("*.txt"))
        reports.extend(self.reports_dir.glob("*.csv"))
        reports.sort(key=lambda p: p.stat().st_mtime, reverse=True)
        return reports[:limit]


# Global instance
report_generator = ReportGenerator()
